# Generated by Django 5.2.1 on 2025-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='provider',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
